### ISSUE TITLE
xxl-job k8s实践 — 老实说

### ISSUE THREAD

**Issue by shidongwa** [shidongwa/blog-comments#84]
https://shidonghua.work/2018/08/06/xxl-job-k8s/ 

 xxl-job-admin 需要读取本地host文件作为集群身份//取executor ip注册到adminStringBuffer triggerMsgSb = new StringBuffer();triggerMsgSb.append(I18nUtil.getString(

**Comment by shidongwa** [comment]
```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "helm.fullname" . }}-headless
  labels:
    app: {{ template "helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "helm.fullname" . }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "helm.name" . }}
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: {{ .Values.service.internalPort | quote }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: xxx
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chmod 777 /xxl-job/logs"]
          volumeMounts:
          - name: log-dir
            mountPath: /xxl-job/logs
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | replace "__string__" "" |  quote }}
          {{- end }}
          volumeMounts:
            - name: log-dir
              mountPath: "/xxl-job/logs"
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          resources:
            {{ toYaml .Values.resources | indent 12 }}
                {{- if .Values.nodeSelector }}
                nodeSelector:
                    {{ toYaml .Values.nodeSelector | indent 8 }}
                {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: log-dir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage }}
```

**Comment by shidongwa** [comment]
```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    app: {{ template "helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "helm.name" . }}
    release: {{ .Release.Name }}
 ```
